---

- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Test influxdb authentication enabled
      block:
        - name: Test creating database without authentication credentials
          command: >
            curl -sPOST "http://localhost:8086/query" \
              --data-urlencode 'q=CREATE DATABASE "test"'
          register: auth_error_response
          failed_when: '"unable to parse authentication credentials" not in auth_error_response.stdout'
          changed_when: false
        - name: Test creating database with authentication credentials
          command: >
            curl -sPOST "http://localhost:8086/query" \
              --data-urlencode 'q=CREATE DATABASE "test"'
              -H 'Authorization: Token {{ influxdb_user_username }}:{{ influxdb_user_password }}'
          register: db_created_response
          failed_when: '"results" not in db_created_response.stdout'
          changed_when: false
      when: influxdb_user_password

    - name: Test influxdb authentication disabled
      block:
        - command: >
            curl -sPOST "http://localhost:8086/query" \
              --data-urlencode 'q=CREATE DATABASE "test"'
          register: db_created_response
          failed_when: '"results" not in db_created_response.stdout'
          changed_when: false
      when: not influxdb_user_password
